name: irllink
description: A mobile application to monitor your IRL stream.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.8.0+87

environment:
  sdk: '>=2.19.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.0
  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  dio: ^5.7.0
  expandable: ^5.0.1
  firebase_analytics: ^11.3.3
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_remote_config: ^5.1.3
  flutter_colorpicker: ^1.1.0
  flutter_foreground_task: ^8.14.0
  flutter_svg: ^2.0.10+1
  flutter_tts: ^4.0.2
  flutter_web_auth: ^0.6.0
  geolocator: ^13.0.1
  get: ^4.6.6
  get_storage: ^2.1.1
  html: ^0.15.4
  http: ^1.2.2
  in_app_purchase: ^3.2.0
  instant: ^0.5.1
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  kick_chat: ^1.6.0
  mobile_scanner: ^6.0.2
  obs_websocket: ^5.1.0+9
  package_info_plus: ^8.1.1
  percent_indicator: ^4.2.3
  qr_flutter: ^4.1.0
  quiver: ^3.2.1
  socket_io_client: ^3.0.0
  split_view: ^3.2.1
  talker_dio_logger: ^4.4.0
  talker_flutter: ^4.4.0
  twitch_chat: ^1.3.2
  upgrader: ^11.3.0
  url_launcher: ^6.3.1
  uuid:  ^4.5.1
  wakelock_plus: ^1.2.8
  web_socket_channel: ^3.0.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^4.1.0
  webview_flutter_wkwebview: ^3.16.3
  cached_network_image: ^3.4.1
  auto_mappr_annotation: ^2.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_mappr: ^2.5.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  integration_test:
    sdk: flutter

dependency_overrides:

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "lib/assets/icon/background.png"
  adaptive_icon_foreground: "lib/assets/icon/foreground.png"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - lib/assets/
     - lib/assets/i18n/
     - lib/assets/twitch/
     - lib/assets/kick/badges/
     - lib/assets/kick/
     - lib/assets/streamelements/
     - lib/assets/youtube/