name: irllink
description: A mobile application to monitor your IRL stream.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.11.1+94

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.2
  collection: ^1.19.0
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  expandable: ^5.0.1

  firebase_analytics: ^11.4.2
  firebase_core: ^3.11.0
  firebase_remote_config: ^5.4.0
  firebase_crashlytics: ^4.3.2
  firebase_messaging: ^15.2.2
  flutter_colorpicker: ^1.1.0
  flutter_foreground_task: ^8.17.0
  flutter_svg: ^2.0.17
  flutter_tts: ^4.2.2
  flutter_web_auth_2: ^4.1.0
  geolocator: ^13.0.2
  get: ^4.7.2
  get_storage: ^2.1.1
  in_app_purchase: ^3.2.1
  instant: ^0.5.1
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  kick_chat: ^1.6.0
  mobile_scanner: ^6.0.6
  obs_websocket: ^5.1.0+9
  package_info_plus: ^8.2.1
  percent_indicator: ^4.2.4
  qr_flutter: ^4.1.0
  quiver: ^3.2.2
  socket_io_client: ^3.0.2
  split_view: ^3.2.1
  talker_dio_logger: ^4.6.11
  talker_flutter: ^4.6.11
  twitch_chat: ^1.3.2
  upgrader: ^11.3.1
  url_launcher: ^6.3.1
  uuid:  ^4.5.1
  wakelock_plus: ^1.2.10
  web_socket_channel: ^3.0.2
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  webview_flutter_wkwebview: ^3.18.1
  cached_network_image: ^3.4.1
  auto_mappr_annotation: ^2.3.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  dartz: ^0.10.1
  flutter_local_notifications: ^18.0.1
  app_links: ^6.3.3
  store_checker: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  auto_mappr: ^2.8.0
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  integration_test:
    sdk: flutter

dependency_overrides:

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - lib/assets/
     - lib/assets/i18n/
     - lib/assets/twitch/
     - lib/assets/kick/badges/
     - lib/assets/kick/
     - lib/assets/streamelements/
     - lib/assets/youtube/