// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP7c-ykoowu1SlhBeAbP3SquFL7Wqiudc',
    appId: '1:1012029402006:android:850b5bda777692251bcbb7',
    messagingSenderId: '1012029402006',
    projectId: 'irl-link',
    storageBucket: 'irl-link.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKiqOZOszxMjPHzNUOmg7LTwlzVGYFRJc',
    appId: '1:1012029402006:ios:b0dc75db1bc354e51bcbb7',
    messagingSenderId: '1012029402006',
    projectId: 'irl-link',
    storageBucket: 'irl-link.appspot.com',
    iosClientId: '1012029402006-s3d36cnvqn9au4slc0fhg3p1e1c28qds.apps.googleusercontent.com',
    iosBundleId: 'dev.lezd.www.irllink',
  );
}
