name: Android Tests

on:
  pull_request:
    branches:
      - master
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.29.2'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Create Android emulator
        run: |
          echo "y" | sdkmanager "system-images;android-33;google_apis;x86_64"
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" -d "pixel_2"

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit and widget tests
        run: flutter test

      - name: Run integration tests
        run: |
          flutter emulators --launch test_emulator
          flutter drive --driver=integration_test/driver.dart --target=integration_test/app_test.dart
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }} 