# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI

on:
  push:
    branches:
      - master
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"
      
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
        
      - working-directory: ${{ inputs.working-directory }}
        run: |
          flutter pub get
          dart analyze
          flutter build apk --debug
          flutter build appbundle --debug
