name: Build Android

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Test connection
        run: curl "https://storage.googleapis.com/flutter_infra_release/releases/releases_linux.json"
      
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create google-services.json
        run: |
          pwd
          cat ./android/app/google-services.json | base64

      - name: Add data to google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > ./android/app/google-services.json

      - name: Build APK and App Bundle
        run: |
          flutter pub get
          dart analyze
          flutter build apk --debug
          flutter build appbundle --debug
